name: Backend Continuous Integration

on:
  pull_request:
    branches: [ main ]
    paths:
      - "starter/backend/**"
      - ".github/workflows/backend-ci.yaml"
  workflow_dispatch:

jobs:
  # Runs in parallel with "test"
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-be-${{ runner.os }}-${{ hashFiles('starter/backend/Pipfile.lock') }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --dev
          pipenv run pip install flake8
      - name: Lint
        run: pipenv run flake8 .

  # Runs in parallel with "lint"
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-be-${{ runner.os }}-${{ hashFiles('starter/backend/Pipfile.lock') }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --dev
          pipenv run pip install pytest
      - name: Test
        run: pipenv run pytest -q

  # Must run only after lint & test succeed
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]   # <- rubric requirement
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t backend-ci-test -f starter/backend/Dockerfile starter/backend

