name: Backend Continuous Integration
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yaml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        working-directory: backend
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Lint
        working-directory: backend
        run: pipenv run pylint .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        working-directory: backend
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Test
        working-directory: backend
        run: pipenv run pytest

  build:
    runs-on: ubuntu-latest
    needs: [ lint, test ]
    steps:
      - uses: actions/checkout@v4
      - name: Build (smoke)
        run: docker build -t movie-backend:ci-test ./backend
