name: Backend Continuous Integration
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "starter/backend/**"
      - ".github/workflows/backend-ci.yaml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps (pipenv + dev)
        working-directory: starter/backend
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --dev
          pipenv run pip install flake8
      - name: Lint (flake8)
        working-directory: starter/backend
        run: pipenv run flake8 .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps (pipenv + dev)
        working-directory: starter/backend
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --dev
          pipenv run pip install pytest
      - name: Run pytest
        working-directory: starter/backend
        run: pipenv run pytest -q

  build:
    runs-on: ubuntu-latest
    needs: [ lint, test ]
    steps:
      - uses: actions/checkout@v4
      - name: Docker build (smoke)
        run: docker build -t movie-backend:ci-test ./starter/backend
