name: Frontend Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "starter/frontend/**"
      - ".github/workflows/frontend-ci.yaml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install deps
        working-directory: starter/frontend
        run: npm ci
      - name: Lint
        working-directory: starter/frontend
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install deps
        working-directory: starter/frontend
        run: npm ci
      - name: Test
        working-directory: starter/frontend
        run: npm test -- --watch=false
